[package]
name = "taletool-zlib"
version = "0.1.0"
publish = false
edition.workspace = true
license = "AGPL-3.0-or-later AND Zlib"
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true

[build-dependencies]
cc.workspace = true

[lints.rust]
unsafe_code = "allow"
